version: "3"

services:
  searchstax-docs-headless-db:
    container_name: searchstax-docs-headless-db
    image: mysql:8
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./configs/config.cnf:/usr/local/bin/config.cnf
      - ./configs/db-backup.sh:/usr/local/bin/db-backup.sh
      - ./configs/db-import.sh:/usr/local/bin/db-import.sh
      - ./configs/database.sql:/usr/local/bin/database.sql
    ports:
      - 3306:3306
    expose:
      - "3306"
    networks:
      - searchstax-docs-headless

  searchstax-docs-headless-cms:
    container_name: searchstax-docs-headless-cms
    image: drupal:10.1.3-php8.2-apache
    ports:
      - 8080:80
    restart: unless-stopped
    volumes:
      - searchstax-docs-headless-cms-data:/var/www/html
      - ./configs/php.ini:/usr/local/etc/php/php.ini
      - ./configs/setup.sh:/usr/local/bin/setup.sh
      - ./configs/services.yml:/opt/drupal/web/sites/default/services.yml
    entrypoint: bash /usr/local/bin/setup.sh
    depends_on:
      - searchstax-docs-headless-db
    networks:
      - searchstax-docs-headless

  searchstax-docs-headless-app:
    container_name: searchstax-docs-headless-app
    image: node:16-alpine
    ports:
      - 3010:3010
    build:
      context: ./react-headless
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./react-headless:/app
      - /app/node_modules
      - ./configs/build.sh:/usr/local/bin/build.sh
      - ./configs/templates/searchstax_studio_react:/templates/searchstax_studio_react

volumes:
  searchstax-docs-headless-cms-data:
  searchstax-docs-headless-db-data:

networks:
  searchstax-docs-headless:
