<?php

/**
 * Implements hook_theme().
 */
function searchstax_studio_react_theme($existing, $type, $theme, $path) {

  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'searchstax_studio_react' => [
      'render element' => 'children',
      'template' => 'searchstax_studio_react',
      'path' => $path . '/templates'
    ],
  ];

}

/**
 * Implements hook_preprocess_page()
 */
function searchstax_studio_react_preprocess_page(&$variables) {
    $variables['#attached']['library'][] = 'searchstax_studio_react/searchstax_studio_react-app';
}
